---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/6/1 22:13
---
-- 用户id
local userId = tonumber(ARGV[1])
-- 管理员未读通知总数
local adminNotificationCount = tonumber(ARGV[2])
-- 所有管理员权限系统通知总数
local allAdminSuperNotificationCount = tonumber(ARGV[3])
-- 管理员已读用户权限系统通知
local adminSuperNotificationCount = tonumber(ARGV[4])
-- 管理员未读通知总数key
local adminNotificationCountKey = "notification:count:" .. userId
-- 所有管理员权限系统通知总数key
local allAdminSuperNotificationCountKey = "allSuperNotification:admin:count"
-- 管理员已读用户权限系统通知key
local adminSuperNotificationKey = "superNotification:admin:count:" .. userId

redis.call("SET",adminNotificationCountKey,adminNotificationCount,"EX",3600)
redis.call("SET",allAdminSuperNotificationCountKey,allAdminSuperNotificationCount)
redis.call("SET",adminSuperNotificationKey,adminSuperNotificationCount,"EX",3600)