---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/2/20 11:09
---

--缓存的帖子id
local forumId = ARGV[1]
--缓存的帖子信息json
local forumJson = ARGV[2]
--缓存的帖子浏览量
local forumPV = ARGV[3]
--缓存过期时间
local TTL = ARGV[4]

local cacheForumKey = 'forum:cache:' .. forumId
local cacheForumPVKey = 'forum:cachePV:' .. forumId


redis.call("SET",cacheForumKey,forumJson,"EX",TTL)
redis.call("HSET",cacheForumPVKey,"PV",forumPV)
redis.call("EXPIRE",cacheForumPVKey,TTL)

