---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/4/7 16:09
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/2/20 11:09
---

--缓存的帖子id
local forumId = ARGV[1]
--续期阈值
local threshold = tonumber(ARGV[2])
--续期目标TTL(秒)
local TTL = tonumber(ARGV[3])

local cacheForumKey = 'forum:cache:' .. forumId
local cacheForumPVKey = 'forum:cachePV:' .. forumId

local forumJson = redis.call("GET", cacheForumKey)

--缓存未命中,交给Java重建
if not forumJson then
    return nil;
end

--查询缓存剩余的时间
local remaining = redis.call("TTL", cacheForumKey)

-- 剩余时间低于阈值则续期（-1 表示永不过期，不处理；-2 表示已不存在，上面已拦截）
if remaining ~= -1 and remaining < threshold then
  redis.call("EXPIRE",cacheForumPVKey,TTL)
  redis.call("EXPIRE",cacheForumKey,TTL)
end

--PV(浏览量自增)
redis.call("HINCRBY",cacheForumPVKey,'PV',1)

return forumJson
