---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/5/30 17:58


-- 未读系统通知数
local noReadSuperNotificationCount = "superNotificationCount"
-- 未读普通通知数
local noReadNotificationCount = "notificationCount"
-- 未读所有通知数
local noReadAllNotificationCount = "allNotificationCount"
-- 当前登录用户id
local userId = tonumber(ARGV[1])
-- 是已读通知还是收到通知 0（已读） 1（收到）
local flag = tonumber(ARGV[2])
-- 操作类型 0（系统通知信息） 1（普通通知信息）
local onType = tonumber(ARGV[3])
-- 用户权限等级
local userLevel = tonumber(ARGV[4])
-- 所有通知总数KEY
local key = 'notification:count:' .. userId
-- 管理员通知总数KEY
local adminKey = "notification:admin:count:" .. userId

if userLevel == 3 then
    if onType == 0 then
        if flag == 0 then
            redis.call("HINCRBY",key,noReadAllNotificationCount,-1)
            redis.call("HINCRBY",key,noReadSuperNotificationCount,-1)
        else
            redis.call("HINCRBY",key,noReadAllNotificationCount,1)
            redis.call("HINCRBY",key,noReadSuperNotificationCount,1)
        end
    else
        if flag == 0 then
            redis.call("HINCRBY",key,noReadAllNotificationCount,-1)
            redis.call("HINCRBY",key,noReadNotificationCount,-1)
        else
            redis.call("HINCRBY",key,noReadAllNotificationCount,1)
            redis.call("HINCRBY",key,noReadNotificationCount,1)
        end
    end
else
    if onType == 0 then
        if flag == 0 then
            redis.call("HINCRBY",adminKey,noReadAllNotificationCount,-1)
            redis.call("HINCRBY",adminKey,noReadSuperNotificationCount,-1)
        else
            redis.call("HINCRBY",adminKey,noReadAllNotificationCount,1)
            redis.call("HINCRBY",adminKey,noReadSuperNotificationCount,1)
        end
    else
        if flag == 0 then
            redis.call("HINCRBY",adminKey,noReadAllNotificationCount,-1)
            redis.call("HINCRBY",adminKey,noReadNotificationCount,-1)
        else
            redis.call("HINCRBY",adminKey,noReadAllNotificationCount,1)
            redis.call("HINCRBY",adminKey,noReadNotificationCount,1)
        end
    end
end




