---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/6/2 0:30
---

-- 用户id
local userId = tonumber(ARGV[1])
-- 用户未读通知总数
local notificationCount = tonumber(ARGV[2])
-- 所有用户权限系统通知总数
local allUserSuperNotificationCount = tonumber(ARGV[3])
-- 用户已读用户权限系统通知
local superNotification = tonumber(ARGV[4])
-- 用户未读通知总数key
local notificationCountKey = "notification:count:" .. userId
-- 用户已读用户权限系统通知key
local superNotificationKey = "superNotification:count:" .. userId
-- 所有用户权限系统通知总数key
local allUserSuperNotificationCountKey = "allSuperNotification:count"


redis.call("SET",notificationCountKey,notificationCount)
redis.call("SET",allUserSuperNotificationCountKey,allUserSuperNotificationCount)
redis.call("SET",superNotificationKey,superNotification)

