---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 63959.
--- DateTime: 2026/8/25 16:44
---

--当前用户1分钟发起请求的次数KEY
local key = ARGV[1]
--当前操作用户id
local userId = ARGV[2]
--限流/分钟内请求 key TTL
local TTL = tonumber(ARGV[3])

--当前用户1分钟发起请求的次数KEY + 当前操作用户id
local finalKey = key .. userId
--限流用户key
local rateLimitingKey = 'request:rateLimiting:' .. userId
--获取当前用户限流key是否存在
local exists = redis.call("EXISTS",rateLimitingKey)
--判断当前用户是否已被限流  1为已限流  0为未限流  若已经限流直接return
if exists == 1 then
    return 0
end
--请求数 + 1
local count = redis.call("INCR",finalKey)
--当当前用户请求数为1时，自动生成TTL
if count == 1 then
    redis.call("EXPIRE",finalKey,TTL)
    return 1
end

--当1分钟内请求次数达到200或者以上，创建针对当前用户的限流key,时间为60s
if count >= 200 then
    redis.call("SET",rateLimitingKey,0,"EX",TTL)
    return 0
else
    --若分钟内请求次数不够则放行
    return 1
end
